//
// AUTOGENERATED FILE
// This code was generated by SwiftSpec
//
// Changes to this file may cause
// incorrect behaviour and will be lost
// if the file is regenerated.
//

import XCTest
import SwiftSpec

class IGNORE_FeaturesWithIgnoreTagAreNotExecutedTests : Ignore {
var testRunner:TestRunner!
var scenarioContext:ScenarioContext!

override func setUp() {
super.setUp()
scenarioContext = ScenarioContextImplementation()
scenarioContext.featureTags = ["ignore"]
testRunner = TestRunner(scenarioContext: scenarioContext)
}

override func tearDown() {
testRunner = nil
scenarioContext = nil
super.tearDown()
}

func testThisScenarioWouldFailIfExecutedTests() {
do {
try testRunner.executeStep(.when, "executing a step that fails")
} catch {
XCTFail("\(error)")
}
}
func testThisScenarioWouldAlsoFailIfExecutedTests() {
do {
try testRunner.executeStep(.when, "executing a step that fails")
} catch {
XCTFail("\(error)")
}
}
}