//
// AUTOGENERATED FILE
// This code was generated by SwiftSpec
// 2016-12-18 08:57:48+0100
//
// Changes to this file may cause
// incorrect behaviour and will be lost
// if the file is regenerated.
//

import XCTest
import SwiftSpec

class ScenariosWithIgnoreTagAreNotExecutedTests : XCTestCase {
var testRunner:TestRunner!

override func setUp() {
super.setUp()
testRunner = TestRunner(scenarioContext: ScenarioContextImplementation())

}

override func tearDown() {
testRunner = nil
super.tearDown()
}

func IGNORE_testThisScenarioWouldFailIfExecutedTests() {
do {
try testRunner.executeStep(.When, "executing a step that fails")
} catch {
XCTFail("\(error)")
}
}
func testThisScenarioWillSucceedWhenExecutedTests() {
do {
try testRunner.executeStep(.When, "executing a step that succeedes")
} catch {
XCTFail("\(error)")
}
}
}
