//
// AUTOGENERATED FILE
// This code was generated by SwiftSpec
// 2016-12-18 08:57:48+0100
//
// Changes to this file may cause
// incorrect behaviour and will be lost
// if the file is regenerated.
//

import XCTest
import SwiftSpec

class StepsParametersArePassedToTheBindingMethodsTests : XCTestCase {
var testRunner:TestRunner!

override func setUp() {
super.setUp()
	testRunner = TestRunner(scenarioContext: ScenarioContextImplementation())

}

override func tearDown() {
testRunner = nil
super.tearDown()
}

func testTableParametersTests() {
do {
let table1 = Table(columns: ["Name", "Balance"])
.addingRow(cells: ["Coffee", "1111"])
.addingRow(cells: ["Computers", "2222"])
try testRunner.executeStep(.Given, "the following accounts", table1)
try testRunner.executeStep(.When, "the balance of account 'Computers' is changed to 3333")
let table2 = Table(columns: ["Name", "Balance"])
.addingRow(cells: ["Coffee", "1111"])
.addingRow(cells: ["Computers", "3333"])
try testRunner.executeStep(.Then, "should accounts as follows exist", table2)
} catch {
XCTFail("\(error)")
}
}
}
