//
// AUTOGENERATED FILE
// This code was generated by SwiftSpec
// 2016-12-18 08:57:48+0100
//
// Changes to this file may cause
// incorrect behaviour and will be lost
// if the file is regenerated.
//

import XCTest
import SwiftSpec

class FeaturesAndScenariosCanHaveAssociatedTagsTests : XCTestCase {
var testRunner:TestRunner!

override func setUp() {
super.setUp()
	testRunner = TestRunner(scenarioContext: ScenarioContextImplementation())
}

override func tearDown() {
testRunner = nil
super.tearDown()
}

func testAFeatureCanHaveTagsTests() {
do {
try testRunner.executeStep(.Then, "this feature has the tag 'featureTag'")
} catch {
XCTFail("\(error)")
}
}
func testAScenarioCanHaveTagsTests() {
do {
try testRunner.executeStep(.Then, "this scenario have the tags 'one', 'two' and 'three'")
} catch {
XCTFail("\(error)")
}
}
}
